include:
  - ./compose-volumes_${VOLUMES:-default}.yml

# Common Django template for GeoNode and Celery services below
x-common-django:
  &default-common-django
  image: ${DOCKER_REGISTRY}${DOCKER_REPOSITORY}${COMPOSE_PROJECT_NAME}_django:${GEONODE_BASE_IMAGE_VERSION}-${PROJECT_VERSION}
  build:
    context: ./docker/geonode
    dockerfile: Dockerfile
    args:
      - BASE_IMAGE_VERSION=${GEONODE_BASE_IMAGE_VERSION}
  restart: always
  extra_hosts:
    - "host.docker.internal:host-gateway"
  env_file:
    - .env
  volumes:
    # configuration
    - ./geonode/geonode/settings_override.py:/usr/src/geonode/geonode/settings_override.py
    - ./geonode/uploaded/subsites:/mnt/volumes/statics/uploaded/subsites
    - ./geonode/uwsgi.ini:/usr/src/geonode/uwsgi.ini
    - ./geonode/fixtures:/usr/src/geonode/fixtures
    # contrib apps
    - ./geonode/apps/customizations:/usr/src/geonode/customizations
    - ./geonode/apps/externalapplications/externalapplications:/usr/src/geonode/externalapplications
    - ./geonode/apps/geonode_sta/geonode_sta:/usr/src/geonode/geonode_sta
    # volumes
    - statics:/mnt/volumes/statics
    - geoserver-data-dir:/geoserver_data/data
    - backup-restore:/backup_restore
    - data:/data
    - tmp:/tmp
  depends_on:
    db:
      condition: service_healthy
    data-dir-conf:
      condition: service_healthy

services:

  #
  # application proxy
  #
  app-proxy:
    image: traefik:${TRAEFIK_IMAGE_VERSION}
    container_name: app-prox4${COMPOSE_PROJECT_NAME}
    restart: always
    command:
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--ping=true"
      - "--accesslog=true"
      - "--accesslog.bufferingsize=0"
    ports:
      - 80:80
      - 127.0.0.1:8100:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - app-proxy:/letsencrypt
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://127.0.0.1:8080/ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s
  #
  #   CMS
  #
  # before adding CMS, activate the according volumes in compose-volumes_infotool.yml
  cms:
    # source: https://hub.docker.com/_/wordpress
    image: wordpress:${WORDPRESS_IMAGE_VERSION}
    container_name: cms4${COMPOSE_PROJECT_NAME}
    restart: always
    env_file:
      - .env.cms
    volumes:
      - ./docker/wordpress/000-default.conf:/etc/apache2/sites-available/000-default.conf:ro
      - cms:/var/www/html
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cms-router.rule=Host(`localhost`) && PathPrefix(`/infotool`)"
      - "traefik.http.routers.cms-router.entrypoints=web"
      - "traefik.http.routers.cms-router.middlewares=cms-add-slash,cms-strip"
      - "traefik.http.middlewares.cms-strip.stripprefix.prefixes=/infotool/"
      - "traefik.http.middlewares.cms-add-slash.redirectregex.regex=^(https?://[^/]+)/infotool$$"
      - "traefik.http.middlewares.cms-add-slash.redirectregex.replacement=$${1}/infotool/"
      - "traefik.http.middlewares.cms-add-slash.redirectregex.permanent=true"
      - "traefik.http.services.cms-service.loadbalancer.server.port=80"
    depends_on:
      cms-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "--user-agent", "CoSiteDockerHealthCheck", "--fail", "--silent", "--write-out", "HTTP CODE : %{http_code}\n", "--output", "/dev/null", "http://127.0.0.1:80/"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s
  cms-db:
    image: mariadb:11.4.10
    container_name: cms-db4${COMPOSE_PROJECT_NAME}
    restart: always
    env_file:
      - .env.cms
    volumes:
      - cms-db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
  #
  #   GEONODE
  #
  # Nginx is serving django static and media files and proxies to django and geonode
  geonode:
    labels:
      - "traefik.enable=true"
      # TODO: switch, if new context path is working/to be tested
      #- "traefik.http.routers.geonode-app.rule=Host(`localhost`) && PathPrefix(`/geonode/`)"
      # TODO: add geoserver redirect
      # TODO: add some geonode redirects
      # TODO: add subsite redirects
      - "traefik.http.routers.geonode-app.rule=Host(`localhost`) && PathPrefix(`/geoportal/`)"
      - "traefik.http.routers.geonode-app.entrypoints=web"
      - "traefik.http.services.geonode-service.loadbalancer.server.port=80"
    image: ${DOCKER_REGISTRY}${DOCKER_REPOSITORY}${COMPOSE_PROJECT_NAME}_nginx:${NGINX_BASE_IMAGE_VERSION}-${PROJECT_VERSION}
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
      args:
        - BASE_IMAGE_VERSION=${NGINX_BASE_IMAGE_VERSION}
    container_name: nginx4${COMPOSE_PROJECT_NAME}
    env_file: .env
    environment:
      - HTTP_HOST=localhost
      - LETSENCRYPT_MODE=disabled
      - RESOLVER=127.0.0.11
    volumes:
      - statics:/mnt/volumes/statics
    restart: always
    healthcheck:
      test: ["CMD", "curl", "--fail", "--silent", "--write-out", "HTTP CODE : %{http_code}\n", "--output", "/dev/null", "http://127.0.0.1:80/nginx-health"]
      interval: 30s
      timeout: 10s
      retries: 3
  # Our custom django application. It includes Geonode.
  django:
    << : *default-common-django
    container_name: django4${COMPOSE_PROJECT_NAME}
    environment:
      - DJANGO_SETTINGS_MODULE=geonode.settings_override
      - IS_CELERY=False
    entrypoint: ["/usr/src/geonode/entrypoint.sh"]
    command: "uwsgi --ini /usr/src/geonode/uwsgi.ini"
    healthcheck:
      test: "curl --fail --silent --write-out 'HTTP CODE : %{http_code}\n' --output /dev/null http://127.0.0.1:8000/"
      start_period: 60s
      interval: 60s
      timeout: 10s
      retries: 10

  # Celery worker that executes celery tasks created by Django.
  celery:
    << : *default-common-django
    container_name: celery4${COMPOSE_PROJECT_NAME}
    depends_on:
      - django
    environment:
      - DJANGO_SETTINGS_MODULE=geonode.settings_override
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672/
      - IS_CELERY=True
    entrypoint: ["/usr/src/geonode/entrypoint.sh"]
    command: "celery-cmd"
    healthcheck:
      test: ["CMD-SHELL", "celery -A geonode.celery_app status || exit 1"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 60s

  # Geoserver backend
  geoserver:
    image: ${DOCKER_REGISTRY}${DOCKER_REPOSITORY}${COMPOSE_PROJECT_NAME}_geoserver:${GEOSERVER_BASE_IMAGE_VERSION}-${PROJECT_VERSION}
    build:
      context: ./docker/geoserver
      dockerfile: Dockerfile
      args:
        - BASE_IMAGE_VERSION=${GEOSERVER_BASE_IMAGE_VERSION}
    container_name: geoserver4${COMPOSE_PROJECT_NAME}
    env_file: ./.env
    volumes:
      - statics:/mnt/volumes/statics
      - geoserver-data-dir:/geoserver_data/data
      - backup-restore:/backup_restore
      - data:/data
      - tmp:/tmp
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      data-dir-conf:
        condition: service_healthy
    init: true
    healthcheck:
      test: "curl --fail --silent --write-out 'HTTP CODE : %{http_code}\n' --output /dev/null http://127.0.0.1:8080/geoserver/ows"
      start_period: 60s
      interval: 60s
      timeout: 10s
      retries: 10

  data-dir-conf:
    image: ${DOCKER_REGISTRY}${DOCKER_REPOSITORY}${COMPOSE_PROJECT_NAME}_gsconf:${GEOSERVER_DATA_BASE_IMAGE_VERSION}-${PROJECT_VERSION}
    build:
      context: ./docker/geoserver_data
      dockerfile: Dockerfile
      args:
        - BASE_IMAGE_VERSION=${GEOSERVER_DATA_BASE_IMAGE_VERSION}
    container_name: gsconf4${COMPOSE_PROJECT_NAME}
    entrypoint: sleep infinity
    volumes:
      - geoserver-data-dir:/geoserver_data/data
    restart: unless-stopped
    healthcheck:
      test: "ls -A '/geoserver_data/data' | wc -l"

  # PostGIS database.
  db:
    image: ${DOCKER_REGISTRY}${DOCKER_REPOSITORY}${COMPOSE_PROJECT_NAME}_db:${POSTGRES_BASE_IMAGE_VERSION}-${PROJECT_VERSION}
    build:
      context: ./docker/postgresql
      dockerfile: Dockerfile
      args:
        - BASE_IMAGE_VERSION=${POSTGRES_BASE_IMAGE_VERSION}
    command: postgres -c "max_connections=${POSTGRES_MAX_CONNECTIONS}"
    container_name: db4${COMPOSE_PROJECT_NAME}
    env_file: ./.env
    volumes:
      - dbdata:/var/lib/postgresql/data
      - dbbackups:/pg_backups
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -U $${POSTGRES_USER:-postgres} -d $${POSTGRES_DB:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Vanilla RabbitMQ service. This is needed by celery
  rabbitmq:
    image: rabbitmq:3-alpine
    container_name: rabbitmq4${COMPOSE_PROJECT_NAME}
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "check_running"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
